version: '3.1'

services:

    web:
        container_name: js-web
        image: nginx:alpine
        env_file:
            - .env.development
        volumes:
            - ./web/nginx.conf:/etc/nginx/nginx.conf
            - ./uploads:/var/www/html/uploads
        ports:
            - 80:80
        links: 
            - server:server
            - client:client

    server:
        container_name: js-server
        image: node:lts-alpine
        working_dir: /home/node/server
        env_file:
            - .env.development
        volumes:
            - ./server:/home/node/server        
        expose:
            - 8080
        ports:
            - 8080:8080
        # depends_on: 
        #     - database
        #     - cache
        command: ["yarn", "dev"]
    
    client:
        container_name: js-client
        image: node:lts-alpine
        working_dir: /home/node/client
        env_file:
            - .env.development
        volumes:
            - ./client:/home/node/client   
        expose:
            - 3000
        ports:
            - 3000:3000
        command: ["yarn", "start"]     
            
    database:
        container_name: js-database
        image: mongo
        env_file:
            - .env.development
        volumes:
            - "./database/data:/data/db"
        restart: unless-stopped
        ports:
            - 27017:27017

    # client:
